export const categoryToCollection: Record<string, string> = {
      Smartphones: "smartphonerecycles",
      Laptop: "laptoprecycles",
      Accessories: "accessoriesrecycles",
      Television: "televisionrecycles",
      Refrigerator: "refrigeratorrecycles",
      Others: "othersrecycles",
      // ... other mappings if needed
      smartphone: "smartphonerecycles",
      smartphones: "smartphonerecycles",
      laptop: "laptoprecycles",
      laptops: "laptoprecycles",
      accessories: "accessoriesrecycles",
      television: "televisionrecycles",
      televisions: "televisionrecycles",
      refrigerator: "refrigeratorrecycles",
      refrigerators: "refrigeratorrecycles",
      other: "othersrecycles",
      others: "othersrecycles",
      redeemed: "redeemeds",
};
